services:

  gestion:
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENVIRONMENT=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASS=secretadmin
      - DB_NAME=cias

  database:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:secretadmin
    volumes:
      - ./data/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
