services:

  gestion:
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENVIRONMENT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=

  database:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:
    volumes:
      - ./data/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
